### ISSUE TITLE
Issue running image on Proxmox LXC

### ISSUE THREAD

**Issue by ufondu88** [NestMTX/app#43]
I pulled the image with Docker compose on a brand new Proxmox LXC, but I get this error
```
info: Loading Preconfigured ICE servers {"service":"ice"}
info: IPC Server listening on /home/node/app/resources/ipc.sock {"service":"ipc"}
info: Updating Database... {"service":"core"}

   Error:
Command
failed
with
exit
code
1:
node
ace
migration:run
--force
[
error
]
unable
to
open
database
file
at
new
Database
(/home/node/app/node_modules/better-sqlite3/lib/database.js:69:26)
at
Client_BetterSQLite3.acquireRawConnection
(/home/node/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12)
at
create
(/home/node/app/node_modules/knex/lib/client.js:262:39)

   at async AppProvider.boot providers/app_provider.js:88
   83|              this.#io.boot(logger);
   84|              await this.#ipc.boot(logger);
   85|              const db = await this.app.container.make('lucid.db');
   86|              const hash = await this.app.container.make('hash');
   87|              this.#logger.info('Updating Database...');
 ❯ 88|              const { stdout } = await execa('node', ['ace', 'migration:run', '--force'], { cwd: base });
   89|              this.#logger.info(stdout);
   90|              const systemUserExists = await db.from('users').where('username', 'system').first();
   91|              if (!systemUserExists) {
   92|                  await db.table('users').insert({
   93|                      id: 0,

   ⁃ new Database
     node_modules/better-sqlite3/lib/database.js:69
   ⁃ Client_BetterSQLite3.acquireRawConnection
     node_modules/knex/lib/dialects/better-sqlite3/index.js:14
   ⁃ create
     node_modules/knex/lib/client.js:262
```

This is the docker compose file content

```
services:
  nestmtx:
    image: nestmtx/amd64:latest
    container_name: nestmtx
    restart: unless-stopped
    environment:
      - RTP_MAX_PORT=10100
      - MEDIA_MTX_RTSP_ENABLED=true
      - MEDIA_MTX_RTMP_ENABLED=true
      - MEDIA_MTX_HLS_ENABLED=true
      - MEDIA_MTX_WEB_RTC_ENABLED=true
      - MEDIA_MTX_SRT_ENABLED=true
    ports:
      - "2000:2000"
      - "2001:2001"
      - "1935:1935"
      - "8000:8000/udp"
      - "8001:8001/udp"
      - "8189:8189/tcp"
      - "8189:8189/udp"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./tmp:/home/node/app/tmp
```
I have no idea what the issue could be
