### ISSUE TITLE
VAAPI Hardware Transcoding Failures

### ISSUE THREAD

**Issue by pyro2927** [NestMTX/app#45]
## Which version are you using?

v1.1.1

## Which operating system are you using?

Ubuntu Server 24.04.1 amd64, Docker version 27.5.0, build a187fa5

CPU: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz

I've verified the system has h264 hardware encoding and decoding capabilities via ffmpeg.

## Describe the issue

When running with `FFMPEG_HW_ACCELERATOR` of `vaapi` or `qsv`, ffmpeg fails to start and streams are unable to be processed.

## Describe how to replicate the issue

1. Start the server
2. Publish with RTSP
3. Read with VLC or any other client (Frigate, ffmpeg, etc)

Example Docker Compose file:
```
  nestmtx:
    image: nestmtx/amd64:latest
    container_name: nestmtx
    restart: unless-stopped
    environment:
      - RTP_MAX_PORT=10100
      - MEDIA_MTX_RTSP_ENABLED=true
      - MEDIA_MTX_RTMP_ENABLED=true
      - MEDIA_MTX_HLS_ENABLED=true
      - MEDIA_MTX_WEB_RTC_ENABLED=true
      - MEDIA_MTX_SRT_ENABLED=true
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - IP_LAN_RESOLVED=192.168.1.80
      - IP_RESOLVERS_ENABLED=cloudflare
      - LOG_LEVEL=debug
      - FFMPEG_HW_ACCELERATOR=vaapi
      - FFMPEG_HW_ACCELERATOR_DEVICE="amd:/dev/dri/renderD128"
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "2000:2000"
      - "2001:2001"
      - "1935:1935"
      - "8000:8000/udp"
      - "8001:8001/udp"
      - "8189:8189/tcp"
      - "8189:8189/udp"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "10000-10100:10000-10100/udp"
```

Also attempted with `FFMPEG_HW_ACCELERATOR=qsv` and had a similar error.

## Attempted Fixes

Tried doing a `chmod -R 777 /dev/dri` on the host before starting the container. Also passed in explicitly the `/dev/dri/renderD128` and `/dev/dri/card0` paths. Confirmed by exec'ing on the container that `/dev/dri/...` is in fact mounted and readable.

## Logs

```
nestmtx  | info: [AVHWDeviceContext @ 0x7eff4fc13c80] Failed to initialise VAAPI connection: -1 (unknown libva error). {"mtx":"front","service":"streamer","stream":"output"}
nestmtx  | info: Device creation failed: -5. {"mtx":"front","service":"streamer","stream":"output"}
nestmtx  | info: Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': I/O error {"mtx":"front","service":"streamer","stream":"output"}
nestmtx  | info: Error parsing global options: I/O error {"mtx":"front","service":"streamer","stream":"output"}
nestmtx  | info: Streamer exited with code 251 {"mtx":"front","service":"streamer"}
nestmtx  | info: ffmpeg -loglevel warning -fflags "+discardcorrupt" -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device "/dev/dri/renderD128" -i "pipe:3" "-c:v" h264_vaapi -vaapi_device "/dev/dri/renderD128" -vf "format=\"nv12,hwupload\"" -tune zerolatency -x264opts "bframes=0" -preset ultrafast "-b:v" 100k -r 10 -pix_fmt yuv420p "-c:a:0" aac "-b:a:0" 128k "-c:a:1" libopus "-b:a:1" 128k -map "0:v:0" -map "0:a:0" -map "0:a:1" -f mpegts -use_wallclock_as_timestamps 1 "\"srt://127.0.0.1:8890/?streamid=publish:driveway&pkt_size=1316\"" {"mtx":"driveway","service":"streamer"}
```

## Network Dump

Not attaching. If I disable hardware acceleration things work correctly (albeit with high CPU utilization).
